application: REPLACE this with your app name <<<<<<<<<<<<<<<<<<<<
version: 1
runtime: python27
module: default
api_version: 1
threadsafe: false

handlers:
- url: /_ah/mail/.+
  script: main.py

inbound_services:
- mail
